name: sexual_app
description: A new Flutter application.
author: Omar Isalgue Begue <omar26begue@gmail.com>

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gradients: ^1.0.0+3
  hexcolor: ^2.0.3
  provider: ^5.0.0
  scoped_model: ^1.1.0
  shared_preferences: ^2.0.5
  retrofit: ^1.3.4+1
  chopper: ^3.0.6
  json_annotation: ^3.1.1
  flutter_svg: ^0.19.3
  cached_network_image: ^2.5.0
  logger: ^1.0.0
  # autentificacion facebook
  flutter_facebook_auth: ^3.3.2+2
  lottie: ^0.5.1
  intl: ^0.17.0
  share: ^2.0.1
  flutter_slider_drawer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.11.0
  build_test: ^1.3.4
  chopper_generator: ^3.0.6
  retrofit_generator: ^1.4.1+3
  json_serializable: ^3.5.1

flutter_icons:
  image_path: "assets/img/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/fonts/

  fonts:
    - family: Quicksand Regular
      fonts:
        - asset: assets/fonts/QUICKSAND-REGULAR.TTF

    - family: Quicksand Blod
      fonts:
        - asset: assets/fonts/QUICKSAND-BOLD.TTF

    - family: Gibson Regular
      fonts:
        - asset: assets/fonts/GIBSONREGULAR.OTF

    - family: Gibson Light
      fonts:
        - asset: assets/fonts/GIBSONLIGHT.OTF

    - family: Gibson SemiBlod
      fonts:
        - asset: assets/fonts/GIBSONSEMIBD.OTF

    - family: Open Sans Regular
      fonts:
        - asset: assets/fonts/OPENSANS-REGULAR.TTF

    - family: Open Sans SemiBlod
      fonts:
        - asset: assets/fonts/OPENSANS-SEMIBOLD.TTF

    - family: Open Sans Blod
      fonts:
        - asset: assets/fonts/OPENSANS-BOLD.TTF
